# Generated by Django 4.2.3 on 2023-07-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userfile_share_profile_photo_note_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
