# Generated by Django 4.2.3 on 2023-07-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='share',
            options={'verbose_name': 'Shared Note', 'verbose_name_plural': 'Shared Notes'},
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, default='Your Note Title', max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='file_size',
            field=models.IntegerField(blank=True, max_length=20),
        ),
    ]
